name: Deploy to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/main
          sudo rm -rf Addition
          git clone https://github.com/Hemantha06/Addition.git
          cd /home/ubuntu/main/Addition
          git checkout main
          git pull origin main
          chmod +x deploy.sh
          ./deploy.sh
